### ISSUE TITLE
When I ran 'hugo server -D', an error occurred.

### ISSUE THREAD

**Issue by tzkyard** [zapatran/hugo-oblate-theme#2]
When I ran `hugo server -D`, an error occurred as follows:
`Building sites … ERROR 2019/04/07 20:35:15 error: failed to transform resource: TOCSS: failed to transform "sass/main.scss" (text/x-scss): this feature is not available in  your current Hugo version                                                                                                                                                    Total in 26 ms                                                                                                                                                               Error: Error building site: logged 1 error(s)`    

And my hugo version is: **`Hugo Static Site Generator v0.54.0-B1A82C61 windows/amd64 BuildDate: 2019-02-01T09:42:02Z`**, so how to deal with this problem?

**Comment by zapatran** [comment]
I don't know, I don't see any problem running with my version. Did you try to update the version? did you install the extended version?

check this [link](https://discourse.gohugo.io/t/solved-error-tocss-failed-to-transform-style-sass-text-x-sass/13776)
